In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
X = np.array([
              [1,1],
              [1,2],
              [2,2],
              [2,3]
])

In [4]:
y = np.dot(X,np.array([1,2])) + 3

In [5]:
y

array([ 6,  8,  9, 11])

In [6]:
lr = LinearRegression()

In [7]:
lr.fit(X,y)

LinearRegression()

In [8]:
lr.predict(np.array([[3,5]]))

array([16.])

In [9]:
import pandas as pd

In [10]:
data = pd.read_csv('D:\Python\Machine-Learning\Regression Algorithms\winequality-red.csv', sep=';')

In [11]:
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [12]:
lr1 = LinearRegression()

In [13]:
# Taking all rows and leaving 11th column
X = data.iloc[:,:11]

In [14]:
# Taking all rows but considering 11th column only
y = data.iloc[:,11]

In [15]:
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [16]:
# Training lr1
lr1.fit(X,y)

LinearRegression()

In [17]:
# Predict
lr1.predict(X)

array([5.03285045, 5.13787975, 5.20989474, ..., 5.94304255, 5.47075621,
       6.00819633])

In [18]:
# Finding score
lr1.score(X,y)

0.3605517030386881